epochs: 300
batch_size: 128
lr: 0.05
min_lr: 1e-3
opt: sgd
weight_decay: 5e-4
sched: multistep
warmup_epochs: 3
color_jitter: 0  # 建议开启
smoothing: 0.1
decay_milestones: [150,200,250]

# epochs: 240
# batch_size: 64
# lr: 0.05
# min_lr: 1e-3
# opt: sgd
# weight_decay: 2e-3
# sched: multistep
# warmup_epochs: 3
# color_jitter: 0
# smoothing: 0.1
# decay_milestones: [150,180,210]

# epochs: 300
# batch_size: 128
# lr: 0.03
# min_lr: 1e-3
# opt: sgd
# weight_decay: 2e-3
# sched: cosine
# warmup_epochs: 3
# color_jitter: 0
# smoothing: 0.1